"""Skill-first agent runtime for quant trading.

Modules:
  - skill: Skill-first routing framework (Skill, SkillRouter, SkillResult)
  - intel_collector: BM25-based intel gathering with source collectors
  - multi_llm_ensemble: Multi-LLM ensemble (GPT-4o + Claude 3.5 + Gemini 1.5)
    with Platt scaling, adaptive weights, and calibration feedback
  - risk_gate: 15+ risk checks with three-stage dry-run safety gate
  - kelly_sizer: Fractional Kelly position sizing with 7 adjustment factors
  - research_team: Multi-agent research team (6 analysts + bull/bear researchers)
  - debate_engine: Bull vs Bear multi-agent debate framework (red-blue confrontation)
  - multi_role_agents: Multi-role agent factory (6+2+3+4 architecture)
  - trading_agents: TradingAgentsCoordinator: 15-agent complete investment loop
  - hedge_fund_agents: Multi-agent hedge fund architecture
    (PortfolioManagerAgent, RiskAnalystAgent, MacroStrategistAgent,
     ExecutionAgent, HedgeFundMultiAgent with run_cycle())
  - finmem_llm: Memory-Augmented LLM Trading Agent (FinMem-LLM-StockTrading port)
    (MemoryContext, FinMemDataPipeline, MemoryAugmentedLLM, FinMemTradingAgent)
"""

from quant_trading.agent.skill import Skill, SkillRouter
from quant_trading.agent.multi_llm_ensemble import (
    MultiLLMEnsemble,
    EnsembleResult,
    ModelPrediction,
    CalibrationResult,
    ConfidenceLevel,
    AggregationMethod,
    compute_adaptive_weights,
    calibrate_probability,
    record_forecast_outcome,
)
from quant_trading.agent.multi_llm_bridge import (
    MultiLLMBridge,
    LLMResponse,
    SUPPORTED_MODELS,
)
from quant_trading.agent.model_ensemble import (
    ModelEnsemble,
    StrategyFilter,
    ModelVote,
    FilterResult,
    EnsembleDecision,
)
from quant_trading.agent.risk_gate import (
    RiskCheckResult,
    MarketFeatures,
    EdgeResult,
    PortfolioState,
    RiskConfig,
    evaluate_risk_gate,
    assess_drawdown,
    check_portfolio_exposure,
    DryRunSafetyGate,
)
from quant_trading.agent.kelly_sizer import (
    PositionSize,
    KellyConfig,
    KellySizer,
    RegimeDetector,
    assess_timeline,
    build_edge_result,
    create_kelly_sizer_skill,
)
from quant_trading.agent.debate_engine import (
    Claim,
    DebateResult,
    DebateAgent,
    BullAgent,
    BearAgent,
    DebateEngine,
    Stance,
)
from quant_trading.agent.multi_role_agents import (
    Role,
    MultiRoleAgentFactory,
)
from quant_trading.agent.research_team import (
    AgentProgressTracker,
    FinancialSituationMemory,
    build_horizon_context,
    create_fundamentals_analyst,
    create_macro_analyst,
    create_market_analyst,
    create_news_analyst,
    create_smart_money_analyst,
    create_social_media_analyst,
    create_bull_researcher,
    create_bear_researcher,
    create_research_manager,
    create_game_theory_manager,
)
from quant_trading.agent.trading_agents import (
    TradingAgentsCoordinator,
    create_llm_client,
    DEFAULT_CONFIG as TRADING_AGENTS_CONFIG,
    create_trader_node,
    create_aggressive_debater_node,
    create_conservative_debater_node,
    create_neutral_debater_node,
    create_risk_manager_node,
)
from quant_trading.agent.agent_quant import (
    ResearchTask,
    ResearchResult,
    RegimeDetector as MarketRegimeDetector,
    WalkForwardValidator,
    AgentQuant,
)
from quant_trading.agent.research_pipeline import (
    ResearchPipeline,
    PipelineStage,
    PipelineReport,
)
from quant_trading.agent.finmem import (
    FinMemCoordinator,
    ProfilingMemory,
    WorkingMemory,
    DecisionMemory,
    MemoryItem,
)
from quant_trading.agent.invest_debate import (
    AnalysisReport,
    TradingDecision,
    AnalystAgent,
    MarketAnalyst,
    SentimentAnalyst,
    NewsAnalyst,
    FundamentalsAnalyst,
    BullResearcher,
    BearResearcher,
    PortfolioManager as InvestPortfolioManager,
    build_llm_client,
    SAFE_LLM_CALL,
)
from quant_trading.agent.portfolio_manager import (
    PortfolioManager,
    PositionState,
    PortfolioRisk,
    compute_allowed_actions,
    compute_position_limits,
    calculate_volatility_metrics,
    calculate_volatility_adjusted_limit,
    calculate_correlation_multiplier,
)
from quant_trading.agent.polymarket_agent import (
    PolymarketAgent,
    FractionalKellySizer,
    RiskCheckResult as PMRiskCheckResult,
    WhaleSignal,
    ResearchResult as PMResearchResult,
    BetResult,
    DryRunSafetyGate as PMDryRunSafetyGate,
)
from quant_trading.agent.polymarket_autonomous import (
    PolymarketAutonomous,
    MultiModelEnsembleTrader,
    RiskGate15,
    FractionalKellySizerV2,
    PlattCalibratorV2,
    DryRunSafetyGate as PMADryRunSafetyGate,
    SelfCalibratingTrader,
    EnsembleDecision,
    ModelForecast,
    MarketSnapshot,
    RiskCheckResult as PMARiskCheckResult,
    RiskGateResult,
    PositionSizeResult,
    CalibrationFeedback,
    TradeDecision,
    ConfidenceLevel,
    Decision,
)
from quant_trading.agent.risk_checks import (
    RiskCheckResult as RCRiskCheckResult,
    RiskCheckSeverity,
    RiskConfig,
    run_risk_checks,
    check_kill_switch,
    check_drawdown,
    check_max_daily_loss,
    check_max_positions,
    check_min_edge,
    check_min_liquidity,
    check_max_spread,
    check_evidence_quality,
    check_confidence_level,
    check_min_implied_prob,
    check_edge_direction,
    check_market_type,
    check_portfolio_exposure,
    check_timeline_endgame,
    check_bankroll_fraction,
    check_min_stake,
)
from quant_trading.agent.calibration import (
    PlattCalibrator,
    CalibrationResult as PMCalibrationResult,
    CalibrationHistory,
    get_global_calibrator,
)
from quant_trading.agent.llm_tradebot import (
    LLMTradeBot,
    ProviderRouter,
    MultiModelVoter,
    AdversarialPipeline,
    TradeExecutor,
    ProviderConfig,
    ChatMessage,
    LLMResponse,
    VoteResult,
    EnsembleResult,
    AdversarialResult,
    TradeDecision,
    Action,
)
from quant_trading.agent.trading_agents_ashare import (
    BullBearDebate,
    AShareResearcher,
    ClaimValidator,
    PortfolioConstructor,
    TradingAgentsAShareCoordinator,
    AShareAnalystReport,
    DebateOutcome,
    PortfolioPosition,
    TradingSignal,
    DEFAULT_LLM_CALL,
    build_llm_client,
    Stance,
    VerdictDirection,
    DataHorizon,
)
from quant_trading.agent.hedge_fund_agents import (
    PortfolioManagerAgent,
    RiskAnalystAgent,
    MacroStrategistAgent,
    ExecutionAgent,
    HedgeFundMultiAgent,
    TradeAction,
    RiskLevel,
    AgentMessage,
    AllocationPlan,
    RiskReport,
    MacroSignal,
    ExecutionResult,
    CycleResult,
)
from quant_trading.agent.finmem_llm import (
    MemoryContext,
    FinMemDataPipeline,
    MemoryAugmentedLLM,
    FinMemTradingAgent,
    LLMCallError,
)
from quant_trading.agent.prism_insight import (
    KoreanStockAnalyzer,
    StockTrackingAgent,
    TelegramBotAdapter,
    WeeklyInsightReport,
    PrismInsightOrchestrator,
    get_market_ohlcv,
    get_nearest_business_day,
)
from quant_trading.agent.ai_broker_agent import (
    TradeDecision,
    BacktestResult,
    BacktestTrade,
    BacktestMetrics,
    StockQuote,
    PolymarketMarket,
    AlpacaConnector,
    Backtester,
    StockQuoteService,
    PolymarketAgent,
    BullBearDebateEngine,
    AIInvestAdvisor,
)

__all__ = [
    # Skill framework
    "Skill",
    "SkillRouter",
    # Multi-LLM ensemble
    "MultiLLMEnsemble",
    "EnsembleResult",
    "ModelPrediction",
    "CalibrationResult",
    "ConfidenceLevel",
    "AggregationMethod",
    "compute_adaptive_weights",
    "calibrate_probability",
    "record_forecast_outcome",
    # Multi-LLM bridge
    "MultiLLMBridge",
    "LLMResponse",
    "SUPPORTED_MODELS",
    # Model ensemble
    "ModelEnsemble",
    "StrategyFilter",
    "ModelVote",
    "FilterResult",
    "EnsembleDecision",
    # Risk gate
    "RiskCheckResult",
    "MarketFeatures",
    "EdgeResult",
    "PortfolioState",
    "RiskConfig",
    "evaluate_risk_gate",
    "assess_drawdown",
    "check_portfolio_exposure",
    "DryRunSafetyGate",
    # Kelly sizer
    "PositionSize",
    "KellyConfig",
    "KellySizer",
    "RegimeDetector",
    "assess_timeline",
    "build_edge_result",
    "create_kelly_sizer_skill",
    # Debate engine
    "Claim",
    "DebateResult",
    "DebateAgent",
    "BullAgent",
    "BearAgent",
    "DebateEngine",
    "Stance",
    # Multi-role agents
    "Role",
    "MultiRoleAgentFactory",
    # Research team
    "AgentProgressTracker",
    "FinancialSituationMemory",
    "build_horizon_context",
    "create_fundamentals_analyst",
    "create_macro_analyst",
    "create_market_analyst",
    "create_news_analyst",
    "create_smart_money_analyst",
    "create_social_media_analyst",
    "create_bull_researcher",
    "create_bear_researcher",
    "create_research_manager",
    "create_game_theory_manager",
    # TradingAgents
    "TradingAgentsCoordinator",
    "create_llm_client",
    "TRADING_AGENTS_CONFIG",
    "create_trader_node",
    "create_aggressive_debater_node",
    "create_conservative_debater_node",
    "create_neutral_debater_node",
    "create_risk_manager_node",
    # AgentQuant
    "ResearchTask",
    "ResearchResult",
    "MarketRegimeDetector",
    "WalkForwardValidator",
    "AgentQuant",
    # Research pipeline
    "ResearchPipeline",
    "PipelineStage",
    "PipelineReport",
    # FinMem
    "FinMemCoordinator",
    "ProfilingMemory",
    "WorkingMemory",
    "DecisionMemory",
    "MemoryItem",
    # Invest debate (Bull vs Bear multi-agent)
    "AnalysisReport",
    "TradingDecision",
    "AnalystAgent",
    "MarketAnalyst",
    "SentimentAnalyst",
    "NewsAnalyst",
    "FundamentalsAnalyst",
    "BullResearcher",
    "BearResearcher",
    "InvestPortfolioManager",
    "build_llm_client",
    "SAFE_LLM_CALL",
    # Portfolio Manager
    "PortfolioManager",
    "PositionState",
    "PortfolioRisk",
    "compute_allowed_actions",
    "compute_position_limits",
    "calculate_volatility_metrics",
    "calculate_volatility_adjusted_limit",
    "calculate_correlation_multiplier",
    # PolymarketAgent
    "PolymarketAgent",
    "FractionalKellySizer",
    "WhaleSignal",
    "BetResult",
    "PMDryRunSafetyGate",
    # polymarket_autonomous
    "PolymarketAutonomous",
    "MultiModelEnsembleTrader",
    "RiskGate15",
    "FractionalKellySizerV2",
    "PlattCalibratorV2",
    "PMADryRunSafetyGate",
    "SelfCalibratingTrader",
    "EnsembleDecision",
    "ModelForecast",
    "MarketSnapshot",
    "PMARiskCheckResult",
    "RiskGateResult",
    "PositionSizeResult",
    "CalibrationFeedback",
    "TradeDecision",
    "ConfidenceLevel",
    "Decision",
    # risk_checks
    "RCRiskCheckResult",
    "RiskCheckSeverity",
    "RiskConfig",
    "run_risk_checks",
    "check_kill_switch",
    "check_drawdown",
    "check_max_daily_loss",
    "check_max_positions",
    "check_min_edge",
    "check_min_liquidity",
    "check_max_spread",
    "check_evidence_quality",
    "check_confidence_level",
    "check_min_implied_prob",
    "check_edge_direction",
    "check_market_type",
    "check_portfolio_exposure",
    "check_timeline_endgame",
    "check_bankroll_fraction",
    "check_min_stake",
    # calibration
    "PlattCalibrator",
    "PMCalibrationResult",
    "CalibrationHistory",
    "get_global_calibrator",
    # TradingAgentsAShare — A-share Bull vs Bear debate
    "BullBearDebate",
    "AShareResearcher",
    "ClaimValidator",
    "PortfolioConstructor",
    "TradingAgentsAShareCoordinator",
    "AShareAnalystReport",
    "DebateOutcome",
    "PortfolioPosition",
    "TradingSignal",
    "DEFAULT_LLM_CALL",
    "build_llm_client",
    "Stance",
    "VerdictDirection",
    "DataHorizon",
    # LLMTradeBot
    "LLMTradeBot",
    "ProviderRouter",
    "MultiModelVoter",
    "AdversarialPipeline",
    "TradeExecutor",
    "ProviderConfig",
    "ChatMessage",
    "LLMResponse",
    "VoteResult",
    "EnsembleResult",
    "AdversarialResult",
    "TradeDecision",
    "Action",
    # hedge_fund_agents
    "PortfolioManagerAgent",
    "RiskAnalystAgent",
    "MacroStrategistAgent",
    "ExecutionAgent",
    "HedgeFundMultiAgent",
    "TradeAction",
    "RiskLevel",
    "AgentMessage",
    "AllocationPlan",
    "RiskReport",
    "MacroSignal",
    "ExecutionResult",
    "CycleResult",
    # prism_insight — Korean KOSPI/KOSDAQ analyzer
    "KoreanStockAnalyzer",
    "StockTrackingAgent",
    "TelegramBotAdapter",
    "WeeklyInsightReport",
    "PrismInsightOrchestrator",
    "get_market_ohlcv",
    "get_nearest_business_day",
    # finmem_llm — Memory-Augmented LLM Trading Agent (FinMem-LLM-StockTrading port)
    "MemoryContext",
    "FinMemDataPipeline",
    "MemoryAugmentedLLM",
    "FinMemTradingAgent",
    "LLMCallError",
    # ai_broker_agent — Multi-agent stock analysis & trading (Alpaca, Finnhub, Bull/Bear debate)
    "TradeDecision",
    "BacktestResult",
    "BacktestTrade",
    "BacktestMetrics",
    "StockQuote",
    "PolymarketMarket",
    "AlpacaConnector",
    "Backtester",
    "StockQuoteService",
    "PolymarketAgent",
    "BullBearDebateEngine",
    "AIInvestAdvisor",
]
