"""Signals subpackage for optopsy.

Provides a library of composable signal functions that generate boolean
Series indicating valid entry/exit dates for options strategies.

Signal functions follow the ``SignalFunc`` callable signature:
    SignalFunc = Callable[[pd.DataFrame], pd.Series[bool]]

All signals can be combined using ``and_signals``, ``or_signals``, and
``sustained``, or wrapped in the ``Signal`` class for fluent ``&`` / ``|``
operator chaining.

Example::
    entry = signal_dates(stocks, rsi_below(threshold=30) & sma_above(200))
    results = op.long_calls(options, entry_dates=entry)
"""

from ._combinators import (
    Signal,
    and_signals,
    custom_signal,
    or_signals,
    signal,
    signal_dates,
    sustained,
)
from ._helpers import SignalFunc
from .calendar_signal import day_of_week
from .iv import iv_rank_above, iv_rank_below
from .momentum import (
    ao_above,
    ao_below,
    cci_above,
    cci_below,
    cmo_above,
    cmo_below,
    fisher_cross_above,
    fisher_cross_below,
    kst_cross_above,
    kst_cross_below,
    macd_cross_above,
    macd_cross_below,
    ppo_cross_above,
    ppo_cross_below,
    roc_above,
    roc_below,
    rsi_above,
    rsi_below,
    smi_cross_above,
    smi_cross_below,
    squeeze_off,
    squeeze_on,
    stoch_above,
    stoch_below,
    stochrsi_above,
    stochrsi_below,
    tsi_cross_above,
    tsi_cross_below,
    uo_above,
    uo_below,
    willr_above,
    willr_below,
)
from .overlap import (
    alma_cross_above,
    alma_cross_below,
    dema_cross_above,
    dema_cross_below,
    ema_cross_above,
    ema_cross_below,
    hma_cross_above,
    hma_cross_below,
    kama_cross_above,
    kama_cross_below,
    sma_above,
    sma_below,
    tema_cross_above,
    tema_cross_below,
    wma_cross_above,
    wma_cross_below,
    zlma_cross_above,
    zlma_cross_below,
)
from .price import (
    consecutive_down,
    consecutive_up,
    daily_return_above,
    daily_return_below,
    drawdown_from_high,
    gap_down,
    gap_up,
    high_of_n_days,
    low_of_n_days,
    price_above,
    price_below,
    price_cross_above,
    price_cross_below,
    rally_from_low,
)
from .trend import (
    adx_above,
    adx_below,
    aroon_cross_above,
    aroon_cross_below,
    chop_above,
    chop_below,
    psar_buy,
    psar_sell,
    supertrend_buy,
    supertrend_sell,
    vhf_above,
    vhf_below,
)
from .volume import (
    ad_cross_above_sma,
    ad_cross_below_sma,
    cmf_above,
    cmf_below,
    mfi_above,
    mfi_below,
    obv_cross_above_sma,
    obv_cross_below_sma,
)
from .volatility import (
    atr_above,
    atr_below,
    bb_above_upper,
    bb_below_lower,
    donchian_above_upper,
    donchian_below_lower,
    kc_above_upper,
    kc_below_lower,
    massi_above,
    massi_below,
    natr_above,
    natr_below,
)

__all__ = [
    # _combinators
    "Signal",
    "and_signals",
    "custom_signal",
    "or_signals",
    "signal",
    "signal_dates",
    "sustained",
    # _helpers
    "SignalFunc",
    # calendar_signal
    "day_of_week",
    # iv
    "iv_rank_above",
    "iv_rank_below",
    # momentum
    "rsi_below",
    "rsi_above",
    "macd_cross_above",
    "macd_cross_below",
    "stoch_below",
    "stoch_above",
    "stochrsi_below",
    "stochrsi_above",
    "willr_below",
    "willr_above",
    "cci_below",
    "cci_above",
    "roc_above",
    "roc_below",
    "ppo_cross_above",
    "ppo_cross_below",
    "tsi_cross_above",
    "tsi_cross_below",
    "cmo_above",
    "cmo_below",
    "uo_above",
    "uo_below",
    "squeeze_on",
    "squeeze_off",
    "ao_above",
    "ao_below",
    "smi_cross_above",
    "smi_cross_below",
    "kst_cross_above",
    "kst_cross_below",
    "fisher_cross_above",
    "fisher_cross_below",
    # overlap
    "sma_below",
    "sma_above",
    "ema_cross_above",
    "ema_cross_below",
    "dema_cross_above",
    "dema_cross_below",
    "tema_cross_above",
    "tema_cross_below",
    "hma_cross_above",
    "hma_cross_below",
    "kama_cross_above",
    "kama_cross_below",
    "wma_cross_above",
    "wma_cross_below",
    "zlma_cross_above",
    "zlma_cross_below",
    "alma_cross_above",
    "alma_cross_below",
    # price
    "price_above",
    "price_below",
    "price_cross_above",
    "price_cross_below",
    "gap_up",
    "gap_down",
    "high_of_n_days",
    "low_of_n_days",
    "daily_return_above",
    "daily_return_below",
    "drawdown_from_high",
    "rally_from_low",
    "consecutive_up",
    "consecutive_down",
    # trend
    "adx_above",
    "adx_below",
    "aroon_cross_above",
    "aroon_cross_below",
    "supertrend_buy",
    "supertrend_sell",
    "psar_buy",
    "psar_sell",
    "chop_above",
    "chop_below",
    "vhf_above",
    "vhf_below",
    # volume
    "mfi_above",
    "mfi_below",
    "obv_cross_above_sma",
    "obv_cross_below_sma",
    "cmf_above",
    "cmf_below",
    "ad_cross_above_sma",
    "ad_cross_below_sma",
    # volatility
    "atr_above",
    "atr_below",
    "bb_above_upper",
    "bb_below_lower",
    "kc_above_upper",
    "kc_below_lower",
    "donchian_above_upper",
    "donchian_below_lower",
    "natr_above",
    "natr_below",
    "massi_above",
    "massi_below",
]
